directory: /home/arg/music
library: /home/arg/music/beets.db
asciify_paths: yes
path_sep_replace: '-'
per_disc_numbering: yes

replace:
  '[\x00-\x1f\x7f]': ''
  '[ ]+': ' '
  '^\s+|\s+$': ''
  '…': '...'
  '–': '-'
  '—': '-'
  '’': "'"
  '‘': "'"
  '“': '"'
  '”': '"'

ui:
  color: yes

import:
  copy: yes
  write: yes
  autotag: yes
  log: /home/arg/music/beets.log
  languages: en,ru
  # from_scratch: yes

plugins:
  - scrub
  - musicbrainz
  # - discogs
  - inline
  - fetchart
  - embedart
  - replaygain
  - lyrics
  - zero
  - mpdupdate

paths:
  default: $albumartist/$year - $album/%if{$multidisc,Disc $disc/}$track - $title

item_fields:
  multidisc: 1 if disctotal > 1 else 0

fetchart:
  auto: yes
  cover_names:
    - cover
  minwidth: 500
  maxwidth: 1024
  quality: 95
  enforce_ratio: 10px
  store_source: yes
  sources:
    - '*'
    # - discogs
  high_resolution: yes

embedart:
  auto: yes
  ifempty: no
  remove_art_file: no

lyrics:
  auto: yes
  force: yes
  synced: no
  print: no
  fallback: ''
  sources:
    - lrclib
    - genius

musicbrainz:
  genres: yes
  # external_ids:
  #   discogs: yes

# discogs:
#   user_token: <token>

scrub:
  auto: yes

replaygain:
  auto: yes
  overwrite: yes
  backend: ffmpeg
  per_disc: yes
  noclip: yes

zero:
  auto: yes
  keep_fields:
    - title
    - artist
    - albumartist
    - album
    - year
    - track
    - tracktotal
    - disc
    - disctotal
    - disctitle
    - genres
    - lyrics
    - language
    - isrc
    - images
    - r128_album_gain
    - r128_track_gain
    - rg_album_gain
    - rg_album_peak
    - rg_track_gain
    - rg_track_peak

mpd:
  host: localhost
  port: 6600
