- name: "Clone dotfiles repository"
  ansible.builtin.git:
    repo: "{{ dotfiles.repository }}"
    dest: "{{ dotfiles.directory }}"
    clone: true
    update: true
  register: "dotfiles_repo"

- name: "Install dotfiles"
  ansible.builtin.make:
    chdir: "{{ dotfiles.directory }}"
    target: "configs"
  when: "dotfiles_repo.changed"
