- name: "Configure firewall"
  community.general.ufw:
    rule: "allow"
    port: "{{ item.port }}"
    proto: "tcp"
    comment: "{{ item.comment }}"
  loop: "{{ ufw_ports }}"

- name: "Enable firewall"
  community.general.ufw:
    state: "enabled"
    default: "deny"
