- name: "Setup Samba"
  ansible.builtin.template:
    src: "samba/smb.conf.j2"
    dest: "/etc/samba/smb.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  register: "samba_config"

- name: "Restart Samba"
  ansible.builtin.systemd:
    name: "smbd"
    state: "restarted"
    enabled: true
  when: "samba_config.changed"
