- name: "Configure SSH server"
  ansible.builtin.template:
    src: "sshd/custom.conf.j2"
    dest: "/etc/ssh/sshd_config.d/10-custom.conf"
    owner: "root"
    group: "root"
    mode: "0600"
  register: "sshd_config"

- name: "Restart SSH server"
  ansible.builtin.systemd_service:
    name: "sshd"
    state: "restarted"
    enabled: true
  when: "sshd_config.changed"
