- name: "Change SSH configuration"
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    state: "present"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - regexp: "^#?PermitRootLogin"
      line: "PermitRootLogin no"
    - regexp: "^#?StrictModes"
      line: "StrictModes yes"
    - regexp: "^#?PubkeyAuthentication"
      line: "PubkeyAuthentication yes"
    - regexp: "^#?HostbasedAuthentication"
      line: "HostbasedAuthentication no"
    - regexp: "^#?PasswordAuthentication"
      line: "PasswordAuthentication no"
    - regexp: "^#?KbdInteractiveAuthentication"
      line: "KbdInteractiveAuthentication no"
    - regexp: "^#?AllowUsers"
      line: "AllowUsers {{ ansible_user }}"
