# GPU and rendering
vo=gpu-next
hwdec=auto-unsafe
gpu-context=wayland
gpu-api=opengl
clipboard-backends=wayland
profile=high-quality
autofit-larger=100%x100%
scale=ewa_lanczos4sharpest
dscale=ewa_lanczos4sharpest

# Audio
ao=pipewire
pipewire-buffer=native
audio-channels=stereo
audio-pitch-correction=yes
audio-file-auto=fuzzy
alang=en,eng,uk,ukr,ru,rus
volume=100
volume-max=150

# Subtitles
slang=en,eng
sub-auto=fuzzy
sub-color='#FFFFFFFF'
sub-border-color='#FF000000'
sub-border-size=2.0
sub-shadow-offset=1

# OSD
osd-playing-msg=${filename}
# osd-scale-by-window=no

# Screenshots
screenshot-format=png
screenshot-png-compression=5
screenshot-high-bit-depth=yes
screenshot-dir=~/pictures/screenshots
screenshot-template="mpv-%05n"

# Misc
terminal=no
wayland-app-id=mpv
