#!/bin/bash

set -eu

echo -e "\U0001f538 Setting up a new Ubuntu 20.04 workstation..."

echo -e "\U0001f538 Upgrading system packages..."
apt update
apt upgrade -y

echo -e "\U0001f538 Installing new packages..."
apt install -q -y docker.io docker-compose mc git neovim zsh tmux mosh ripgrep wget fzf universal-ctags

echo -e "\U0001f538 Installing additional tools..."
curl -sLS -o 1password.zip "https://cache.agilebits.com/dist/1P/op/pkg/v1.8.0/op_linux_amd64_v1.8.0.zip"
unzip 1password.zip op -d /usr/local/bin
rm 1password.zip

echo -e "\U0001f538 Setting firewall rules..."
ufw default deny incoming
ufw allow OpenSSH
ufw allow mosh

echo -e "\U0001f538 Creating group for SSH login..."
addgroup sshusers

echo -e "\U0001f538 Creating user..."
adduser --disabled-password arg
usermod -a -G sudo,docker,sshusers -s /usr/bin/zsh arg
sudo -H -u arg sh -c 'mkdir $HOME/.ssh'
sudo -H -u arg sh -c 'chmod 0700 $HOME/.ssh'
echo -e "\U0001f538 Now paste your public SSH key end press <Return>"
read public_key
sudo -H -u arg sh -c 'touch $HOME/.ssh/authorized_keys'
echo $public_key > /home/arg/.ssh/authorized_keys
sudo -H -u arg sh -c 'chmod 0600 $HOME/.ssh/authorized_keys'

echo -e "\U0001f538 Updating configuration files..."
sed -i "s/^PermitRootLogin/#&/" /etc/ssh/sshd_config
sed -i "s/^IgnoreUserKnownHosts/#&/" /etc/ssh/sshd_config
sed -i "s/^PasswordAuthentication/#&/" /etc/ssh/sshd_config
sed -i "s/^PermitTunnel/#&/" /etc/ssh/sshd_config
sed -i "s/^AllowAgentForwarding/#&/" /etc/ssh/sshd_config
sed -i "s/^AllowTcpForwarding/#&/" /etc/ssh/sshd_config
sed -i "s/^X11Forwarding/#&/" /etc/ssh/sshd_config

echo "PermitRootLogin no" >> /etc/ssh/sshd_config.d/user.conf
echo "IgnoreUserKnownHosts yes" >> /etc/ssh/sshd_config.d/user.conf
echo "PasswordAuthentication no" >> /etc/ssh/sshd_config.d/user.conf
echo "PermitTunnel no" >> /etc/ssh/sshd_config.d/user.conf
echo "AllowAgentForwarding no" >> /etc/ssh/sshd_config.d/user.conf
echo "AllowTcpForwarding no" >> /etc/ssh/sshd_config.d/user.conf
echo "X11Forwarding no" >> /etc/ssh/sshd_config.d/user.conf
echo "AllowGroups sshusers" >> /etc/ssh/sshd_config.d/user.conf

echo "arg ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/1-user.conf
chmod 0440 /etc/sudoers.d/1-user.conf

echo ""
echo -e "\U0001f539 Everything done. Press <Return> to reboot the machine with new settings."
read
ufw --force enable
reboot
