#!/usr/bin/env bash

set -eu

dotfiles_path="$HOME/.dotfiles"

echo "**************************"
echo "* Installing dotfiles... *"
echo "**************************"

git clone https://github.com/arg/dotfiles.git $dotfiles_path
cd $dotfiles_path
git remote set-url origin git@github.com:arg/dotfiles.git

if [[ `uname` == "FreeBSD" ]]; then
  gmake
else
  make
fi

echo "**************************************************************************"
echo "* Dotfiles have been successfully installed. Press <Return> to continue. *"
echo "**************************************************************************"
read
