music_directory "/home/arg/music"
playlist_directory "/home/arg/.local/share/mpd/playlists"

db_file "/home/arg/.local/share/mpd/database"
log_file "/home/arg/.local/state/mpd/log"
pid_file "/home/arg/.local/state/mpd/pid"
state_file "/home/arg/.local/state/mpd/state"
sticker_file "/home/arg/.local/share/mpd/sticker.sql"

bind_to_address "127.0.0.1"
port "6600"

audio_output {
    type "pipewire"
    name "PipeWire Output"
    replay_gain_handler "mixer"
}

auto_update "no"
restore_paused "yes"

replaygain "auto"
replaygain_limit "yes"
replaygain_preamp "-15"
replaygain_missing_preamp "-15"
