monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.usb-Focusrite_Scarlett_18i20_4th_Gen_.*HiFi__Line3__sink"
      }
    ]
    actions = {
      update-props = {
        priority.session = 2000
        priority.driver = 2000
      }
    }
  }
]
