#!/usr/bin/env bash

set -eu

echo "************************************************"
echo "* Setting up a new Ubuntu 20.04 workstation... *"
echo "************************************************"

echo "**********************************"
echo "* Adding package repositories... *"
echo "**********************************"

apt-add-repository ppa:fish-shell/release-3 -y

echo "********************************"
echo "* Upgrading system packages... *"
echo "********************************"

apt update
apt upgrade -y

echo "******************************"
echo "* Installing new packages... *"
echo "******************************"

apt install -q -y docker.io docker-compose fish fzf git make mc mosh p7zip-full ripgrep tmux wget

echo "**********************************"
echo "* Installing additional tools... *"
echo "**********************************"

curl -sLS -o 1password.zip "https://cache.agilebits.com/dist/1P/op/pkg/v1.8.0/op_linux_amd64_v1.8.0.zip"
7z e -y -o/usr/local/bin 1password.zip op 1>/dev/null
rm 1password.zip

echo "*****************************"
echo "* Setting firewall rules... *"
echo "*****************************"

ufw default deny incoming
ufw allow OpenSSH
ufw allow mosh
ufw --force enable

echo "**********************"
echo "* Setting up user... *"
echo "**********************"

id -u arg &>/dev/null || adduser --disabled-password arg
usermod -a -G sudo,docker -s /usr/bin/fish arg

echo "***********************************"
echo "* Updating configuration files... *"
echo "***********************************"

sed -i "s/^PermitRootLogin/#&/" /etc/ssh/sshd_config
sed -i "s/^IgnoreUserKnownHosts/#&/" /etc/ssh/sshd_config
sed -i "s/^PasswordAuthentication/#&/" /etc/ssh/sshd_config
sed -i "s/^PermitTunnel/#&/" /etc/ssh/sshd_config
sed -i "s/^AllowAgentForwarding/#&/" /etc/ssh/sshd_config
sed -i "s/^AllowTcpForwarding/#&/" /etc/ssh/sshd_config
sed -i "s/^X11Forwarding/#&/" /etc/ssh/sshd_config

echo "PermitRootLogin no" >> /etc/ssh/sshd_config.d/user.conf
echo "IgnoreUserKnownHosts yes" >> /etc/ssh/sshd_config.d/user.conf
echo "PasswordAuthentication no" >> /etc/ssh/sshd_config.d/user.conf
echo "PermitTunnel no" >> /etc/ssh/sshd_config.d/user.conf
echo "AllowAgentForwarding no" >> /etc/ssh/sshd_config.d/user.conf
echo "AllowTcpForwarding no" >> /etc/ssh/sshd_config.d/user.conf
echo "X11Forwarding no" >> /etc/ssh/sshd_config.d/user.conf
echo "AllowUsers arg" >> /etc/ssh/sshd_config.d/user.conf

echo "arg ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

echo "{\"hosts\": [\"tcp://0.0.0.0:2375\", \"unix:///var/run/docker.sock\"]}" > /etc/docker/daemon.json
mkdir -p /etc/systemd/system/docker.service.d
tee /etc/systemd/system/docker.service.d/override.conf > /dev/null <<EOT
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd
EOT
systemctl daemon-reload
systemctl restart docker

timedatectl set-timezone Europe/Madrid

echo "********************************************************************************"
echo "* Everything done, press <Return> to exit.                                     *"
echo "* Now you may install dotfiles by 'arg' user (see Readme for the instruction). *"
echo "********************************************************************************"
read
