volumes:
  mariadb_data:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.2,nolock,hard,rw,noatime,nfsvers=3"
      device: ":/mnt/storage/network/mariadb"
  monica_data:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.2,nolock,hard,rw,noatime,nfsvers=3"
      device: ":/mnt/storage/network/monica"
  photos_data:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.2,nolock,hard,ro,noatime,nfsvers=3"
      device: ":/mnt/storage/photos"

services:
  traefik:
    image: "traefik:v2.9"
    command:
      - "--ping=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.http.tls.certresolver=letsencrypt"
      - "--entrypoints.websecure.http.tls.domains[0].main=arg.network"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.arg.network"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.letsencrypt.acme.email=arg@arg.zone"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--serverstransport.insecureskipverify=true"
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - "network.env"
    volumes:
      - "/home/arg/network/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/localtime:/etc/localtime:ro"
    healthcheck:
      test: "traefik healthcheck --ping"

  portainer:
    image: "portainer/portainer-ce:2.15.1-alpine"
    restart: "no"
    security_opt:
      - "no-new-privileges:true"
    volumes:
      - "/home/arg/network/portainer:/data"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      traefik.enable: true
      traefik.http.services.portainer.loadbalancer.server.port: 9000
      traefik.http.routers.portainer.rule: "Host(`portainer.arg.network`)"
      traefik.http.routers.portainer.entrypoints: "websecure"
      traefik.http.routers.portainer.tls.certresolver: "letsencrypt"
    healthcheck:
      test: "wget -q --spider 'http://localhost:9000'"

  mariadb:
    image: "mariadb:10.9"
    restart: "no"
    env_file:
      - "network.env"
    volumes:
      - "mariadb_data:/var/lib/mysql"
      - "${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql:ro"
    command: "--transaction-isolation=READ-COMMITTED --log-bin=mysqld-bin --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed"
    healthcheck:
       test: "mysqladmin --silent --user=root --password=$${MARIADB_ROOT_PASSWORD} ping"

  monica:
    image: "monica:3.7-apache"
    restart: "no"
    depends_on:
      - "mariadb"
    env_file:
      - "network.env"
    environment:
      DB_HOST: "mariadb"
      DB_USERNAME: "monica"
      DB_PASSWORD: "monica"
      APP_ENV: "production"
      APP_DISABLE_SIGNUP: true
      APP_TRUSTED_PROXIES: "*"
      APP_URL: "https://monica.arg.network"
    volumes:
      - "monica_data:/var/www/html/storage"
    labels:
      traefik.enable: true
      traefik.http.services.monica.loadbalancer.server.port: 80
      traefik.http.routers.monica.rule: "Host(`monica.arg.network`)"
      traefik.http.routers.monica.entrypoints: "websecure"
      traefik.http.routers.monica.tls.certresolver: "letsencrypt"
    healthcheck:
      test: "curl --output /dev/null --silent --head --fail 'http://localhost:80' || exit 1"

  photoprism:
    image: "photoprism/photoprism:latest"
    restart: "no"
    depends_on:
      - "mariadb"
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: "insecure"
      PHOTOPRISM_AUTH_MODE: "public"
      PHOTOPRISM_SITE_URL: "https://photoprism.arg.network"
      PHOTOPRISM_ORIGINALS_LIMIT: 100
      PHOTOPRISM_LOG_LEVEL: "warning"
      PHOTOPRISM_READONLY: true
      PHOTOPRISM_DISABLE_WEBDAV: true
      PHOTOPRISM_DISABLE_TENSORFLOW: true
      PHOTOPRISM_JPEG_QUALITY: 95
      PHOTOPRISM_DATABASE_DRIVER: "mysql"
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"
      PHOTOPRISM_DATABASE_NAME: "photoprism"
      PHOTOPRISM_DATABASE_USER: "photoprism"
      PHOTOPRISM_DATABASE_PASSWORD: "photoprism"
      PHOTOPRISM_SITE_CAPTION: "Family photos"
      PHOTOPRISM_SITE_AUTHOR: "Andrii Gladkyi"
      PHOTOPRISM_UID: 1000
      PHOTOPRISM_GID: 1000
    volumes:
      - "photos_data:/photoprism/originals"
      - "/home/arg/network/photoprism:/photoprism/storage"
    labels:
      traefik.enable: true
      traefik.http.services.photoprism.loadbalancer.server.port: 2342
      traefik.http.routers.photoprism.rule: "Host(`photoprism.arg.network`)"
      traefik.http.routers.photoprism.entrypoints: "websecure"
      traefik.http.routers.photoprism.tls.certresolver: "letsencrypt"
    healthcheck:
      test: "curl --output /dev/null --silent --head --fail 'http://localhost:2342' || exit 1"
