volumes:
  movies:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.100.2,nolock,rw,soft,nfsvers=3"
      device: ":/volume1/video/movies"

  music:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.100.2,nolock,rw,soft,nfsvers=3"
      device: ":/volume1/music"

services:
  db:
    image: "postgres:14.1-alpine"
    restart: "no"
    volumes:
      - "/home/arg/storage/postgresql:/var/lib/postgresql/data"
      - "/etc/localtime:/etc/localtime:ro"
    env_file:
      - "network.env"
    healthcheck:
      test: "pg_isready --username=$${POSTGRES_USER} --dbname=$${POSTGRES_DB}"

  redis:
    # Redis requires "vm.overcommit_memory = 1" to be set in /etc/sysctl.conf
    image: "redis:6-alpine"
    restart: "no"
    volumes:
      - "/home/arg/storage/redis:/data"
      - "/etc/localtime:/etc/localtime:ro"
    command: "redis-server --save 10 1"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  traefik:
    image: "traefik:v2.5"
    command:
      - "--ping=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.http.tls.certresolver=letsencrypt"
      - "--entrypoints.websecure.http.tls.domains[0].main=arg.network"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.arg.network"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.letsencrypt.acme.email=arg@arg.zone"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--serverstransport.insecureskipverify=true"
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - "network.env"
    volumes:
      - "/home/arg/storage/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/localtime:/etc/localtime:ro"
    healthcheck:
      test: "traefik healthcheck --ping"

  adminer:
    image: "adminer:4-standalone"
    depends_on:
      db:
        condition: service_healthy
    restart: "no"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
      - "traefik.http.routers.adminer.rule=Host(`adminer.arg.network`)"
      - "traefik.http.routers.adminer.entrypoints=websecure"
      - "traefik.http.routers.adminer.tls.certresolver=letsencrypt"
    healthcheck:
      test: "curl --output /dev/null --silent --head --fail 'http://localhost:8080' || exit 1"

  portainer:
    image: "portainer/portainer-ce:2.11.0-alpine"
    restart: "no"
    security_opt:
      - "no-new-privileges:true"
    volumes:
      - "/home/arg/storage/portainer:/data"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.rule=Host(`portainer.arg.network`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
    healthcheck:
      test: "wget -q --spider 'http://localhost:9000'"

  nextcloud:
    image: "linuxserver/nextcloud:23.0.0"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: "no"
    volumes:
      - "/home/arg/storage/nextcloud/config:/config"
      - "/home/arg/storage/nextcloud/data:/data"
    env_file:
      - "network.env"
      - "linuxserver.env"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.nextcloud.loadbalancer.server.scheme=https"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=443"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.arg.network`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls.certresolver=letsencrypt"
    healthcheck:
      test: "curl --output /dev/null --silent --head --fail 'http://localhost:80' || exit 1"

  radarr:
    image: "linuxserver/radarr:latest"
    restart: "no"
    volumes:
      - "/home/arg/storage/radarr:/config"
      - "movies:/movies"
      - "/home/arg/storage/downloads:/downloads"
    env_file:
      - "linuxserver.env"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      - "traefik.http.routers.radarr.rule=Host(`radarr.arg.network`)"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.tls.certresolver=letsencrypt"
    healthcheck:
      test: "curl --output /dev/null --silent --head --fail 'http://localhost:7878' || exit 1"

  qbittorrent:
    image: "linuxserver/qbittorrent:latest"
    restart: "no"
    volumes:
      - "/home/arg/storage/qbittorrent:/config"
      - "/home/arg/storage/downloads:/downloads"
    environment:
      WEBUI_PORT: 8080
    env_file:
      - "linuxserver.env"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
      - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.arg.network`)"
      - "traefik.http.routers.qbittorrent.entrypoints=websecure"
      - "traefik.http.routers.qbittorrent.tls.certresolver=letsencrypt"
    healthcheck:
      test: "curl --output /dev/null --silent --head --fail 'http://localhost:8080' || exit 1"

  jackett:
    image: "linuxserver/jackett:latest"
    restart: "no"
    volumes:
      - "/home/arg/storage/jackett:/config"
      - "/home/arg/storage/downloads:/downloads"
    environment:
      AUTO_UPDATE: "true"
    env_file:
      - "linuxserver.env"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.jackett.loadbalancer.server.port=9117"
      - "traefik.http.routers.jackett.rule=Host(`jackett.arg.network`)"
      - "traefik.http.routers.jackett.entrypoints=websecure"
      - "traefik.http.routers.jackett.tls.certresolver=letsencrypt"
    healthcheck:
      test: "curl --output /dev/null --silent --head --fail 'http://localhost:9117' || exit 1"

  lidarr:
    image: "linuxserver/lidarr:latest"
    restart: "no"
    volumes:
      - "/home/arg/storage/lidarr:/config"
      - "music:/music"
      - "/home/arg/storage/downloads:/downloads"
    env_file:
      - "linuxserver.env"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.lidarr.loadbalancer.server.port=8686"
      - "traefik.http.routers.lidarr.rule=Host(`lidarr.arg.network`)"
      - "traefik.http.routers.lidarr.entrypoints=websecure"
      - "traefik.http.routers.lidarr.tls.certresolver=letsencrypt"
    healthcheck:
      test: "curl --output /dev/null --silent --head --fail 'http://localhost:8686' || exit 1"
