services:
  traefik:
    image: "traefik:v2.9"
    command:
      - "--ping=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.http.tls.certresolver=letsencrypt"
      - "--entrypoints.websecure.http.tls.domains[0].main=arg.network"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.arg.network"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.letsencrypt.acme.email=arg@arg.zone"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--serverstransport.insecureskipverify=true"
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - "network.env"
    volumes:
      - "/home/arg/network/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/localtime:/etc/localtime:ro"
    healthcheck:
      test: "traefik healthcheck --ping"

  mariadb:
    image: "mariadb:10.9"
    restart: "no"
    env_file:
      - "network.env"
    volumes:
      - "/home/arg/network/mariadb:/var/lib/mysql"
      - "${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql:ro"

  portainer:
    image: "portainer/portainer-ce:2.15.1-alpine"
    restart: "no"
    security_opt:
      - "no-new-privileges:true"
    volumes:
      - "/home/arg/network/portainer:/data"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      traefik.enable: true
      traefik.http.services.portainer.loadbalancer.server.port: 9000
      traefik.http.routers.portainer.rule: "Host(`portainer.arg.network`)"
      traefik.http.routers.portainer.entrypoints: "websecure"
      traefik.http.routers.portainer.tls.certresolver: "letsencrypt"
    healthcheck:
      test: "wget -q --spider 'http://localhost:9000'"

  monica:
    image: "monica:3.7-apache"
    restart: "no"
    depends_on:
      - mariadb
    env_file:
      - "network.env"
    environment:
      DB_HOST: "mariadb"
      DB_USERNAME: "monica"
      DB_PASSWORD: "monica"
      APP_ENV: "production"
      APP_DISABLE_SIGNUP: true
      APP_TRUSTED_PROXIES: "*"
      APP_URL: "https://monica.arg.network"
    volumes:
      - "/home/arg/network/monica:/var/www/html/storage"
    labels:
      traefik.enable: true
      traefik.http.services.monica.loadbalancer.server.port: 80
      traefik.http.routers.monica.rule: "Host(`monica.arg.network`)"
      traefik.http.routers.monica.entrypoints: "websecure"
      traefik.http.routers.monica.tls.certresolver: "letsencrypt"
