- name: "Recreate and restart network services"
  hosts: "docker_hosts"
  tasks:
    - name: "docker compose up (force-recreate)"
      community.docker.docker_compose_v2:
        project_src: "{{ docker_directory }}"
        state: "present"
        recreate: "always"
        pull: "never"
        wait: true
        wait_timeout: 120
      register: "compose_restart"

    - name: "Show containers health"
      ansible.builtin.debug:
        msg: "{{ compose_restart.containers | items2dict(key_name='Service', value_name='Health') }}"
