- name: "Start network services"
  hosts: "docker_hosts"
  tasks:
    - name: "docker compose up"
      community.docker.docker_compose_v2:
        project_src: "{{ docker_directory }}"
        state: "present"
        recreate: "never"
        pull: "missing"
        wait: true
        wait_timeout: 120
      register: "compose_up"

    - name: "Show containers health"
      ansible.builtin.debug:
        msg: "{{ compose_up.containers | items2dict(key_name='Service', value_name='Health') }}"
