- name: "Start Network services"
  hosts: "docker_hosts"
  tasks:
    - name: "Run `docker-compose up`"
      community.docker.docker_compose_v2:
        project_src: "~/.dotfiles/network"
        state: "present"
        recreate: "never"
