- name: "Stop network services"
  hosts: "docker_hosts"
  tasks:
    - name: "docker compose stop"
      community.docker.docker_compose_v2:
        project_src: "{{ project_directory }}"
        state: "stopped"
