- name: 'Portainer'
  description: 'Docker management'
  url: 'https://portainer.arg.network'
  hostname: 'portainer.arg.network'
  location: 'Altair'
- name: 'Adminer'
  description: 'Database management'
  url: 'https://adminer.arg.network'
  hostname: 'adminer.arg.network'
  location: 'Altair'
- name: 'IT-Tools'
  description: 'Tools for developers'
  url: 'https://tools.arg.network'
  hostname: 'tools.arg.network'
  location: 'Altair'
- name: 'FreshRSS'
  description: 'RSS reader'
  url: 'https://freshrss.arg.network'
  hostname: 'freshrss.arg.network'
  location: 'Altair'
- name: 'Monica'
  description: 'Contacts management'
  url: 'https://monica.arg.network'
  hostname: 'monica.arg.network'
  location: 'Altair'
- name: 'Plex'
  description: 'Media streaming'
  url: 'https://plex.arg.network'
  hostname: 'plex.arg.network'
  location: 'Altair'
- name: 'Radarr'
  description: 'Movies organizer'
  url: 'https://radarr.arg.network'
  hostname: 'radarr.arg.network'
  location: 'Altair'
- name: 'Sonarr'
  description: 'TV shows organizer'
  url: 'https://sonarr.arg.network'
  hostname: 'sonarr.arg.network'
  location: 'Altair'
- name: 'Prowlarr'
  description: 'Indexer management'
  url: 'https://prowlarr.arg.network'
  hostname: 'prowlarr.arg.network'
  location: 'Altair'
- name: 'qBittorrent'
  description: 'BitTorrent client'
  url: 'https://downloads.arg.network'
  hostname: 'downloads.arg.network'
  location: 'Altair'
