- name: 'IPMI'
  description: 'Supermicro IPMI interface'
  url: 'https://ipmi.arg.network'
  hostname: 'ipmi.arg.network'
  location: 'Sirius'

- name: 'Zabbix'
  description: 'Network monitoring'
  url: 'https://zabbix.arg.network'
  hostname: 'zabbix.arg.network'
  location: 'Polaris'

- name: 'Portainer'
  description: 'Container management'
  url: 'https://portainer.arg.network'
  hostname: 'portainer.arg.network'
  location: 'Polaris'

- name: 'Plex'
  description: 'Media streaming'
  url: 'https://plex.arg.network'
  hostname: 'plex.arg.network'
  location: 'Polaris'

- name: 'Radarr'
  description: 'Movies organizer'
  url: 'https://radarr.arg.network'
  hostname: 'radarr.arg.network'
  location: 'Polaris'

- name: 'Sonarr'
  description: 'TV shows organizer'
  url: 'https://sonarr.arg.network'
  hostname: 'sonarr.arg.network'
  location: 'Polaris'

- name: 'Prowlarr'
  description: 'Indexer management'
  url: 'https://prowlarr.arg.network'
  hostname: 'prowlarr.arg.network'
  location: 'Polaris'

- name: 'qBittorrent'
  description: 'BitTorrent client'
  url: 'https://downloads.arg.network'
  hostname: 'downloads.arg.network'
  location: 'Polaris'

- name: 'Monica'
  description: 'Contacts management'
  url: 'https://monica.arg.network'
  hostname: 'monica.arg.network'
  location: 'Polaris'

- name: 'IT-Tools'
  description: 'Tools for developers'
  url: 'https://tools.arg.network'
  hostname: 'tools.arg.network'
  location: 'Polaris'
