- name: 'Photo Station'
  description: 'Photo gallery'
  url: 'https://photos.arg.network'
  hostname: 'photos.arg.network'
  location: 'Polaris'
- name: 'File Station'
  description: 'File browser'
  url: 'https://files.arg.network'
  hostname: 'files.arg.network'
  location: 'Polaris'
- name: 'Portainer'
  description: 'Container management'
  url: 'https://portainer.arg.network'
  hostname: 'portainer.arg.network'
  location: 'Sirius'
- name: 'Plex'
  description: 'Media server'
  url: 'https://plex.arg.network'
  hostname: 'plex.arg.network'
  location: 'Polaris'
- name: 'qBittorrent'
  description: 'Torrent downloader'
  url: 'https://qbittorrent.arg.network'
  hostname: 'qbittorrent.arg.network'
  location: 'Sirius'
- name: 'Jackett'
  description: 'Torrent search'
  url: 'https://jackett.arg.network'
  hostname: 'jackett.arg.network'
  location: 'Sirius'
- name: 'Radarr'
  description: 'Movie organizer'
  url: 'https://radarr.arg.network'
  hostname: 'radarr.arg.network'
  location: 'Sirius'
- name: 'Sonarr'
  description: 'TV show organizer'
  url: 'https://sonarr.arg.network'
  hostname: 'sonarr.arg.network'
  location: 'Sirius'
- name: 'Lidarr'
  description: 'Music organizer'
  url: 'https://lidarr.arg.network'
  hostname: 'lidarr.arg.network'
  location: 'Sirius'
