- name: 'Monit'
  description: 'Monitoring tool'
  url: 'https://antares.arg.network'
  hostname: 'antares.arg.network'
  location: 'Antares'
- name: 'Files'
  description: 'File manager'
  url: 'https://files.arg.network'
  hostname: 'files.arg.network'
  location: 'Polaris'
- name: 'Photos'
  description: 'Photo library'
  url: 'https://photos.arg.network'
  hostname: 'photos.arg.network'
  location: 'Polaris'
