- name: 'Portainer'
  description: 'Container management'
  url: 'https://portainer.arg.network'
  hostname: 'portainer.arg.network'
  location: 'Antares'
- name: 'Monica'
  description: 'Contacts'
  url: 'https://monica.arg.network'
  hostname: 'monica.arg.network'
  location: 'Antares'
