- name: "Power on ESXi guests"
  hosts: "localhost"
  gather_facts: false
  vars_files:
    - "../../secrets.yml"
  tasks:
    - name: "Power on guest"
      community.vmware.vmware_guest_powerstate:
        hostname: "{{ esxi.hostname }}"
        username: "{{ esxi.username }}"
        password: "{{ esxi.password }}"
        validate_certs: false
        state: "powered-on"
        state_change_timeout: 10
        name: "{{ item }}"
      with_items: "{{ groups['virtual_machines'] }}"
