backups:
  logs_path: "/var/log/rclone"
  sources:
    - path: "/home/arg/vault/archives"
      hour: "1"
    - path: "/home/arg/vault/backups"
      hour: "3"
    - path: "/home/arg/vault/photos"
      hour: "5"
    - path: "/home/arg/vault/veronika"
      hour: "7"
    - path: "/home/arg/vault/videos"
      hour: "9"
