zfs:
  encrypted_credentials_directory: "/etc/credstore.encrypted"
  encrypted_dataset: "zroot/home"
  pools:
    - "archive"
    - "apps"
    - "media"
  targets:
    - "/home/arg/apps"
    - "/home/arg/media"
    - "/home/arg/archive"
  snapshots:
    hourly: 0
    daily: 15
    monthly: 12
  snapshot_datasets:
    - "archive/archives"
    - "archive/backups"
    - "archive/photos"
    - "archive/veronika"
    - "archive/videos"
