zfs:
  encrypted_credentials_directory: "/etc/credstore.encrypted"
  encrypted_dataset: "zroot/home"
  pools:
    - "zroot"
  snapshots:
    hourly: 0
    daily: 15
    monthly: 12
  snapshot_datasets:
    - "zroot/home/vault"
