#!/bin/sh

for branch in $(git for-each-ref --format='%(refname:short)' -- refs/heads/); do
  git config branch.${branch}.rebase true;
  echo "autorebase was set for ${branch} branch"
done

echo ""

git config branch.autosetuprebase always
echo "autorebase was set for all future local branches"
