#!/bin/sh

for branch in $(git for-each-ref --format='%(refname:short)' -- refs/heads/); do
  git config branch.${branch}.rebase true;
  echo "rebase was set for ${branch} branch"
done

git config pull.rebase true
echo "rebase was set to be default strategy"
