#!/bin/bash

set -eu

dotfiles_path="$HOME/.dotfiles"
update_dotfiles=1
fetch_secrets=0
silent=0

while [[ "$#" -gt 0 ]]; do
  case $1 in
    --noupdate) update_dotfiles=0;;
    --secrets) fetch_secrets=1;;
    --silent) silent=1;;
  esac
  shift
done

if [[ $update_dotfiles == 1 ]]; then
  echo -e "\U0001f538 Updating dotfiles..."
  git -C $dotfiles_path pull --rebase
fi

rsync -avh --no-perms $dotfiles_path/home/ ~

if [[ $fetch_secrets == 1 ]]; then
  read -p "What is your 1Password email? " -e op_email
  eval $(op signin https://my.1password.com $op_email)
  echo -e "\U0001f538 Updating GPG keys..."
  temp_file=`mktemp`
  op get document "Personal GPG Keys" > $temp_file
  export GPG_TTY=$(tty)
  tar -Ozxf $temp_file ownertrust.asc | gpg --import-ownertrust
  tar -Ozxf $temp_file private.asc | gpg --import
  tar -Ozxf $temp_file public.asc | gpg --import
  shred --remove=wipesync $temp_file
  echo -e "\U0001f538 Updating SSH keys..."
  temp_name=`mktemp`
  op get document "Personal SSH Keys" > $temp_file
  tar -zxf $temp_file -C $HOME/.ssh
  chmod 0600 $HOME/.ssh/*
  shred --remove=wipesync $temp_file
fi

if [[ $silent == 0 ]]; then
  echo -e "\U0001f539 Dotfiles have been successfully synchronized."
fi
