- name: "Setup Ubuntu Server"
  hosts: "servers"
  become: true

  tasks:
    - import_tasks: "setup/ssh.yml"
      tags: ["ssh"]

    - import_tasks: "setup/system.yml"
      tags: ["system"]

    - import_tasks: "setup/swap.yml"
      tags: ["swap"]

    - import_tasks: "setup/firewall.yml"
      tags: ["firewall"]

    - import_tasks: "setup/journal.yml"
      tags: ["journal"]

    - import_tasks: "setup/packages.yml"
      tags: ["packages"]

    - import_tasks: "setup/dbus.yml"
      tags: ["dbus"]

    - import_tasks: "setup/zfs.yml"
      tags: ["zfs"]

    - import_tasks: "setup/samba.yml"
      tags: ["samba"]

    - import_tasks: "setup/docker.yml"
      tags: ["docker"]

    - import_tasks: "setup/backups.yml"
      tags: ["backups"]

    - import_tasks: "setup/users.yml"
      tags: ["users"]

    - import_tasks: "setup/dotfiles.yml"
      become: false
      tags: ["dotfiles"]
