all:
  vars:
    ansible_user: arg
  hosts:
    sun:
      ansible_host: "192.168.0.3"
    sirius:
      ansible_host: "192.188.0.4"
    polaris:
      ansible_host: "192.168.0.5"
    antares:
      ansible_host: "192.168.0.6"
    deneb:
      ansible_host: "192.168.0.7"
  children:
    virtual_machines:
      hosts:
        polaris:
        antares:
    docker_hosts:
      hosts:
        antares:
