all:
  vars:
    ansible_ssh_common_args: '-o "SetEnv TERM=dumb"'
  hosts:
    polaris:
      ansible_host: "192.168.0.6"
  children:
    servers:
      hosts:
        polaris:
      vars:
        ansible_user: "arg"
        ansible_become: true
        ansible_become_user: "root"
        ansible_become_method: "su"
        ansible_become_exe: "sudo su -"
        additional_users:
          - "veronika"
        dotfiles_dir: "/home/arg/.dotfiles"
        systemd:
          path: "/usr/lib/systemd"
          journal_size: "2G"
        zramswap:
          - name: "PERCENT"
            value: "15"
          - name: "ALGO"
            value: "lz4"
        sysctl_vars:
          - name: "vm.swappiness"
            value: "10"
        grub:
          custom_cmdline: "fbcon=rotate:1 video=1920x1080 consoleblank=300"
        zfs:
          encrypted_credentials_directory: "/etc/credstore.encrypted"
          encrypted_dataset: "zroot/home"
          pools:
            - "archive"
            - "apps"
            - "media"
          targets:
            - "/home/arg/apps"
            - "/home/arg/media"
            - "/home/arg/archive"
          snapshots:
            hourly: 0
            daily: 15
            monthly: 12
          snapshot_datasets:
            - "archive/archives"
            - "archive/backups"
            - "archive/photos"
            - "archive/veronika"
            - "archive/videos"
        packages:
          install:
            - "fish"
            - "fzf"
            - "git"
            - "neovim"
            - "htop"
            - "mc"
            - "tmux"
            - "build-essential"
            - "rsyslog-gnutls"
            - "samba"
            - "rclone"
            - "curl"
            - "wget"
            - "docker.io"
            - "docker-compose-v2"
            - "vifm"
            - "nvme-cli"
            - "zfsutils-linux"
            - "sanoid" # ZFS snapshot management
            - "zram-tools" # ZRAM support
            - "drm-info" # GPU information
            - "libtss2-rc0t64" # TPM2 support
            - "monit"
          remove:
            - "snapd"
        ufw:
          ports:
            - 80
            - 443
          services:
            - "OpenSSH"
            - "Samba"
        samba:
          veto_files:
            - "._*"
            - ".DS_Store"
            - "Thumbs.db"
            - "*.icloud"
            - ".metadata"
            - ".localized"
            - ".Spotlight-V100"
            - ".Trashes"
            - ".fseventsd"
            - ".DocumentRevisions-V100"
          shares:
            - name: "downloads"
              path: "/home/arg/media/downloads"
              guest: false
              read_only: false
            - name: "literature"
              path: "/home/arg/archive/literature"
              guest: false
              read_only: false
            - name: "software"
              path: "/home/arg/media/software"
              guest: true # unauthenticated users should be able to access software directory
              read_only: false
              user: "arg, veronika"
            - name: "videos"
              path: "/home/arg/media/videos"
              guest: false
              read_only: false
            - name: "archives"
              path: "/home/arg/archive/archives"
              guest: false
              read_only: true
            - name: "backups"
              path: "/home/arg/archive/backups"
              guest: false
              read_only: true
            - name: "photos"
              path: "/home/arg/archive/photos"
              guest: false
              read_only: true
              user: "arg, veronika"
            - name: "veronika"
              path: "/home/arg/archive/veronika"
              guest: false
              read_only: true
              user: "veronika"
        backup:
          logs_path: "/var/log/rclone"
          sources:
            - path: "/home/arg/archive/archives"
              hour: "1"
            - path: "/home/arg/archive/backups"
              hour: "3"
            - path: "/home/arg/archive/photos"
              hour: "5"
            - path: "/home/arg/archive/veronika"
              hour: "7"
            - path: "/home/arg/archive/videos"
              hour: "9"
        docker:
          directory: "/docker"
    docker_hosts:
      hosts:
        polaris:
      vars:
        ansible_user: "arg"
        project_directory: "/docker"
