all:
  hosts:
    polaris:
      ansible_host: "192.168.0.6"
  children:
    servers:
      hosts:
        polaris:
      vars:
        ansible_become: true
        ansible_become_user: "root"
        ansible_become_method: "su"
        ansible_become_exe: "sudo su -"
    docker_hosts:
      hosts:
        polaris:
