all:
  vars:
    ansible_user: arg
  hosts:
    sun:
      ansible_host: "192.168.0.3"
    sirius:
      ansible_host: "192.188.0.5"
    polaris:
      ansible_host: "192.168.0.6"
  children:
    servers:
      hosts:
        polaris:
    ipmi_hosts:
      hosts:
        sirius:
    docker_hosts:
      hosts:
        polaris:
