all:
  hosts:
    sirius:
      ansible_host: "192.188.0.5"
    polaris:
      ansible_host: "192.168.0.6"
  children:
    servers:
      hosts:
        polaris:
      vars:
        ansible_user: "arg"
        dotfiles_dir: "/home/arg/.dotfiles"
        systemd_path: "/usr/lib/systemd"
        zswap_percent: "15"
        sysctl_vars:
          - name: "vm.swappiness"
            value: "10"
        zfs_targets:
          - "/home/arg/apps"
          - "/home/arg/media"
          - "/home/arg/archive"
        apt_cache_valid_time: 86400 # 24 hours
        packages_to_install:
          - "fish"
          - "fzf"
          - "git"
          - "neovim"
          - "htop"
          - "mc"
          - "tmux"
          - "build-essential"
          - "rsyslog-gnutls"
          - "samba"
          - "rclone"
          - "curl"
          - "wget"
          - "docker.io"
          - "docker-compose-v2"
          - "vifm"
          - "nvme-cli"
          - "zfsutils-linux"
          - "zram-tools"
          - "drm-info"
        packages_to_remove:
          - "snapd"
        ufw:
          ports:
            - 80
            - 443
          services:
            - "OpenSSH"
            - "Samba"
        samba:
          veto_files:
            - "._*"
            - ".DS_Store"
            - "Thumbs.db"
            - "*.icloud"
            - ".metadata"
            - ".localized"
            - ".Spotlight-V100"
            - ".Trashes"
            - ".fseventsd"
            - ".DocumentRevisions-V100"
          shares:
            - name: "downloads"
              path: "/home/arg/media/downloads"
              guest: false
              read_only: false
            - name: "literature"
              path: "/home/arg/archive/literature"
              guest: false
              read_only: false
            - name: "software"
              path: "/home/arg/media/software"
              guest: true # unauthenticated users should be able to access software directory
              read_only: false
            - name: "videos"
              path: "/home/arg/media/videos"
              guest: false
              read_only: false
            - name: "archives"
              path: "/home/arg/archive/archives"
              guest: false
              read_only: true
            - name: "backups"
              path: "/home/arg/archive/backups"
              guest: false
              read_only: true
            - name: "photos"
              path: "/home/arg/archive/photos"
              guest: false
              read_only: true
            - name: "veronika"
              path: "/home/arg/archive/veronika"
              guest: false
              read_only: true
              user: "veronika"
    ipmi_hosts:
      hosts:
        sirius:
      vars:
        ansible_user: "ADMIN"
    docker_hosts:
      hosts:
        polaris:
      vars:
        ansible_user: "arg"
